Device reboot while application installation is in progress
se-edge/framework-diagrams pull request #3
Opened 2020-06-01 15:06 UTC by damienklotz77

2020-06-10 03:51 UTC, JeremieFiniel approved these changes

2020-06-10 06:58 UTC, lmussier commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +In this usecase, edgemanager reboot interrupts desired processing and occurs before step save instance in storage
Attention de bien spécifier que c'est une exemple et que ce n'est pas toujours le cas.
En gros c'est pas le use case qui veux ça mais l'instance de use case

2020-06-10 07:03 UTC, lmussier commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +User -> Host : edgemanager is started
il start pas EM lui, il start le device du coup le host ici

2020-06-10 07:04 UTC, lmussier commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +EM -> EM : edgemanager bootstraps
c'est confusing, c'est pas sur lui même, ça mériterais une note

2020-06-10 07:08 UTC, lmussier commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +EM -> EM : edgemanager bootstraps
J'ajouterais que, du debut à ici, je ne pense pas que ce soit nécessaire.
Le use case démarre à l'installtion de l'app pas au premier boot du device si je ne me trompe pas

2020-06-10 07:12 UTC, lmussier commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +Hub --> EM : receives full twin for device desired state
juste recive full twin, on choppe les deux (desired et reported)

2020-06-10 07:16 UTC, lmussier requested changes
Le démarrage à modifier pour moi

2020-06-10 11:27 UTC, damienklotz77 commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +In this usecase, edgemanager reboot interrupts desired processing and occurs before step save instance in storage
Corrected

2020-06-10 11:28 UTC, damienklotz77 commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +User -> Host : edgemanager is started
Début du diagramme hors sujet supprimé.

2020-06-10 11:28 UTC, damienklotz77 commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +EM -> EM : edgemanager bootstraps
Corrected

2020-06-10 11:28 UTC, damienklotz77 commented on Usecases/Install-application/Reboot-while-application-installation-is-in-progress.puml
> +Hub --> EM : receives full twin for device desired state
Corrected

2020-06-11 15:24 UTC, lmussier approved these changes

2020-06-11 16:09 UTC, merged