PlantUml Reboot and restoration of the device desired states
se-edge/framework-diagrams pull request #6
Opened 2020-06-23 11:33 UTC by damienklotz77

2020-06-23 12:22 UTC, JeremieFiniel commented on UseCases/Reboot-behavior/Reboot-and-restoration-of-the-device-desired-states.puml
> +... starting application ...
Je comprend pas bien se starting application, l'EM fait une action pour starter l'application ?

2020-06-23 12:22 UTC, JeremieFiniel commented on UseCases/Reboot-behavior/Reboot-and-restoration-of-the-device-desired-states.puml
> +... starting application ...
Là encore, il y a une action faite par l'EM ? l'EM attend quelque chose ?

2020-06-23 13:13 UTC, damienklotz77 commented on UseCases/Reboot-behavior/Reboot-and-restoration-of-the-device-desired-states.puml
> +... starting application ...
J'ai fait quelques changements, je te laisse regarder.

2020-06-23 13:13 UTC, damienklotz77 commented on UseCases/Reboot-behavior/Reboot-and-restoration-of-the-device-desired-states.puml
> +... starting application ...
J'ai fait quelques changements, je te laisse regarder.

2020-06-23 13:19 UTC, JeremieFiniel approved these changes

2020-06-24 14:13 UTC, lmussier commented on UseCases/Reboot-behavior/Reboot-with-already-effective-desired-states.puml
> +Stor --> EM : information of device installed applications and their saved desired status
a mon sens pas utile, le retour est évident et ne fait qu'alourdir le machin

2020-06-24 14:13 UTC, lmussier commented on UseCases/Reboot-behavior/Reboot-with-already-effective-desired-states.puml
> +Hub --> EM : receives full twin for device new desired and reported states
juste full twin non ?

2020-06-24 14:14 UTC, lmussier commented on UseCases/Reboot-behavior/Reboot-with-already-effective-desired-states.puml
> +EM --> Hub : send updated reported twin state starting
pourquoi --> plutot que -> ?

2020-06-24 14:15 UTC, lmussier commented on UseCases/Reboot-behavior/Reboot-with-already-effective-desired-states.puml
> +EM --> Hub : send updated reported twin state running
pourquoi --> plutot que -> ?

2020-06-24 14:28 UTC, lmussier requested changes
Il faudrait mettre plus clairement que sur la première remontée de twin nous avons un transitoir que nous ne pouvons masquer

2020-06-24 14:40 UTC, damienklotz77 commented on UseCases/Reboot-behavior/Reboot-with-already-effective-desired-states.puml
> +Stor --> EM : information of device installed applications and their saved desired status
Corrected

2020-06-24 14:40 UTC, damienklotz77 commented on UseCases/Reboot-behavior/Reboot-with-already-effective-desired-states.puml
> +Hub --> EM : receives full twin for device new desired and reported states
Corrected

2020-06-24 14:40 UTC, damienklotz77 commented on UseCases/Reboot-behavior/Reboot-with-already-effective-desired-states.puml
> +EM --> Hub : send updated reported twin state starting
Corrected

2020-06-24 14:40 UTC, damienklotz77 commented on UseCases/Reboot-behavior/Reboot-with-already-effective-desired-states.puml
> +EM --> Hub : send updated reported twin state running
Corrected

2020-06-24 14:51 UTC, damienklotz77 commented
> Il faudrait mettre plus clairement que sur la première remontée de twin nous avons un transitoir que nous ne pouvons masquer

Corrected

2020-06-24 16:08 UTC, lmussier approved these changes

2020-06-24 17:29 UTC, merged