First commit for config
se-edge/framework-diagrams pull request #8
Opened 2020-07-17 10:30 UTC by lmussier

2020-07-17 14:16 UTC, DeuxVis requested changes
Du coup pas d'interruption avant la fin de la liste en cas d'erreur sur un fichier ?

Ça peut être un choix de vouloir recevoir toutes les erreurs d'un coup, j'ai pas d'avis tranché.

2020-07-17 14:16 UTC, DeuxVis commented on config-states-and-events.puml
> +  :check intégrity;
Typo : Pas d'accents en Anglais

2020-07-17 14:16 UTC, DeuxVis commented on config-states-and-events.puml
> +  : Make sure there is no package id in reporteed twin;
Typo : un **e** en trop.

2020-07-17 14:19 UTC, DeuxVis commented on config-states-and-events.puml
> +  : Make sure there is no package id in reporteed twin;
Aussi sur le fond : si il y avait un package id avant dans le reported (c'est une mise à jour) on l'enlève quand même en cas d'erreur ? Ou bien est-ce que la mise à jour de config n'est pas encore gérée ?

2020-07-17 14:43 UTC, lmussier commented on config-states-and-events.puml
> +  : Make sure there is no package id in reporteed twin;
on le fait sauter en cas d'erreur, mais pas toujours.
Il y à eu une modif de spec...

2020-07-20 06:17 UTC, JeremieFiniel approved these changes

2020-07-21 12:01 UTC, DeuxVis commented on config-states-and-events.puml
> +  : Make sure there is no package id in reporteed twin;
Il reste un "report**ee**d ligne 41 sinon c'est tout bon pour moi.

2020-07-21 12:03 UTC, DeuxVis approved these changes

2020-07-21 12:05 UTC, guillaumemugerin approved these changes

2020-07-21 12:06 UTC, damienklotz77 approved these changes

2020-07-21 13:27 UTC, merged